version: '3'

services:
  database:
    image: postgres:14
    volumes:
      - vol_sk_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sk_example_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sk_example_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "admin"]
      interval: 3s
      timeout: 3s
      retries: 3
    restart: always

  backend:
    image: imoskalenkoxvx/super-kassa:v1
    environment:
      PS_DB: sk_example_db
      PS_USER: sk_example_user
      PS_PASSWORD: admin
      PS_HOST: database
    depends_on:
      database:
        condition: service_healthy
    restart: always
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_started

volumes:
  vol_sk_db: