server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://${PS_HOST}:5432/${PS_DB}
    driver-class-name: org.postgresql.Driver
    username: ${PS_USER}
    password: ${PS_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      platform: postgres
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  file:
    name: logger.log
  level:
    org:
      springframework: INFO